import type { Metadata } from 'next';
import { Cormorant_Infant, Piazzolla, Cormorant } from 'next/font/google';
import cn from 'classnames';

import "@uploadthing/react/styles.css";
import './globals.css';

const titleFont = Cormorant_Infant({ subsets: ['cyrillic'], weight: ['300', '400', '500', '600', '700'], variable: '--title-font' });
const subtitleFont = Piazzolla({ weight: ['400'], subsets: ['cyrillic'], variable: '--subtitle-font' });
const mainTextFont = Cormorant({ subsets: ['cyrillic'], variable: '--main-font', weight: ['300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout(
  {
  children,
}: RootLayoutProps) {
  return (
    <html lang="ru" className={cn(titleFont.variable, subtitleFont.variable, mainTextFont.variable)}>
      <body className={cn(mainTextFont.className)}>
        {children}
      </body>
    </html>
  );
}
